/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package dev.hathora.cloud_api.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class LoginResponse {
    @JsonProperty("token")
    public String token;

    public LoginResponse withToken(String token) {
        this.token = token;
        return this;
    }
    
    public LoginResponse(@JsonProperty("token") String token) {
        this.token = token;
  }
}
