/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package dev.hathora.cloud_api.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PaymentMethod - Make all properties in T optional
 */

public class PaymentMethod {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ach")
    public AchPaymentMethod ach;

    public PaymentMethod withAch(AchPaymentMethod ach) {
        this.ach = ach;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card")
    public CardPaymentMethod card;

    public PaymentMethod withCard(CardPaymentMethod card) {
        this.card = card;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("link")
    public LinkPaymentMethod link;

    public PaymentMethod withLink(LinkPaymentMethod link) {
        this.link = link;
        return this;
    }
    
    public PaymentMethod(){}
}
