/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package dev.hathora.cloud_api.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class VerificationEmailRequest {
    @JsonProperty("userId")
    public String userId;

    public VerificationEmailRequest withUserId(String userId) {
        this.userId = userId;
        return this;
    }
    
    public VerificationEmailRequest(@JsonProperty("userId") String userId) {
        this.userId = userId;
  }
}
