workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    java-source:
        inputs:
            - location: https://hathora.dev/swagger.json
        registry:
            location: registry.speakeasyapi.dev/hathora/hathora/java-source
targets:
    hathora-java:
        target: java
        source: java-source
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/hathora/hathora/code-samples-java-hathora-java
