workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    java-source:
        inputs:
            - location: https://hathora.dev/swagger.json
        registry:
            location: registry.speakeasyapi.dev/hathora/hathora/java-source
targets:
    hathora-java:
        target: java
        source: java-source
        publish:
            java:
                ossrhUsername: 9BQq3qir
                ossrhPassword: $ossrh_password
                gpgSecretKey: $gpg_secret_key
                gpgPassPhrase: $gpg_pass_phrase
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/hathora/hathora/code-samples-java-hathora-java
