/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.hathora.hathora_cloud_sdk.models.operations;

import com.hathora.hathora_cloud_sdk.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class GetLatestDeploymentRequestBuilder {

    private Optional<String> appId = Optional.empty();
    private final SDKMethodInterfaces.MethodCallGetLatestDeployment sdk;

    public GetLatestDeploymentRequestBuilder(SDKMethodInterfaces.MethodCallGetLatestDeployment sdk) {
        this.sdk = sdk;
    }
                
    public GetLatestDeploymentRequestBuilder appId(java.lang.String appId) {
        Utils.checkNotNull(appId, "appId");
        this.appId = Optional.of(appId);
        return this;
    }

    public GetLatestDeploymentRequestBuilder appId(java.util.Optional<java.lang.String> appId) {
        Utils.checkNotNull(appId, "appId");
        this.appId = appId;
        return this;
    }

    public GetLatestDeploymentResponse call() throws Exception {

        return sdk.getLatestDeployment(
            appId);
    }
}
