/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.hathora.cloud_sdk.models.shared.CreateOrgToken;
import dev.hathora.cloud_sdk.utils.SpeakeasyMetadata;
import dev.hathora.cloud_sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;

public class CreateOrgTokenRequest {

    @SpeakeasyMetadata("request:mediaType=application/json")
    private CreateOrgToken createOrgToken;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=orgId")
    private String orgId;

    @JsonCreator
    public CreateOrgTokenRequest(
            CreateOrgToken createOrgToken,
            String orgId) {
        Utils.checkNotNull(createOrgToken, "createOrgToken");
        Utils.checkNotNull(orgId, "orgId");
        this.createOrgToken = createOrgToken;
        this.orgId = orgId;
    }

    @JsonIgnore
    public CreateOrgToken createOrgToken() {
        return createOrgToken;
    }

    @JsonIgnore
    public String orgId() {
        return orgId;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public CreateOrgTokenRequest withCreateOrgToken(CreateOrgToken createOrgToken) {
        Utils.checkNotNull(createOrgToken, "createOrgToken");
        this.createOrgToken = createOrgToken;
        return this;
    }

    public CreateOrgTokenRequest withOrgId(String orgId) {
        Utils.checkNotNull(orgId, "orgId");
        this.orgId = orgId;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateOrgTokenRequest other = (CreateOrgTokenRequest) o;
        return 
            Objects.deepEquals(this.createOrgToken, other.createOrgToken) &&
            Objects.deepEquals(this.orgId, other.orgId);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            createOrgToken,
            orgId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateOrgTokenRequest.class,
                "createOrgToken", createOrgToken,
                "orgId", orgId);
    }
    
    public final static class Builder {
 
        private CreateOrgToken createOrgToken;
 
        private String orgId;
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder createOrgToken(CreateOrgToken createOrgToken) {
            Utils.checkNotNull(createOrgToken, "createOrgToken");
            this.createOrgToken = createOrgToken;
            return this;
        }

        public Builder orgId(String orgId) {
            Utils.checkNotNull(orgId, "orgId");
            this.orgId = orgId;
            return this;
        }
        
        public CreateOrgTokenRequest build() {
            return new CreateOrgTokenRequest(
                createOrgToken,
                orgId);
        }
    }
}
