/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations;

import static dev.hathora.cloud_sdk.operations.Operations.RequestOperation;

import dev.hathora.cloud_sdk.SDKConfiguration;
import dev.hathora.cloud_sdk.models.shared.AppConfig;
import dev.hathora.cloud_sdk.operations.CreateAppV1DeprecatedOperation;
import dev.hathora.cloud_sdk.utils.Utils;
import java.lang.Exception;

public class CreateAppV1DeprecatedRequestBuilder {

    private AppConfig request;
    private final SDKConfiguration sdkConfiguration;

    public CreateAppV1DeprecatedRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public CreateAppV1DeprecatedRequestBuilder request(AppConfig request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CreateAppV1DeprecatedResponse call() throws Exception {
        
        RequestOperation<AppConfig, CreateAppV1DeprecatedResponse> operation
              = new CreateAppV1DeprecatedOperation( sdkConfiguration);

        return operation.handleResponse(operation.doRequest(request));
    }
}
