/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations;

import static dev.hathora.cloud_sdk.operations.Operations.RequestOperation;

import dev.hathora.cloud_sdk.SDKConfiguration;
import dev.hathora.cloud_sdk.operations.GetApps;
import dev.hathora.cloud_sdk.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import java.util.Optional;

public class GetAppsRequestBuilder {

    private Optional<String> orgId = Optional.empty();
    private final SDKConfiguration sdkConfiguration;

    public GetAppsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public GetAppsRequestBuilder orgId(String orgId) {
        Utils.checkNotNull(orgId, "orgId");
        this.orgId = Optional.of(orgId);
        return this;
    }

    public GetAppsRequestBuilder orgId(Optional<String> orgId) {
        Utils.checkNotNull(orgId, "orgId");
        this.orgId = orgId;
        return this;
    }


    private GetAppsRequest buildRequest() {

        GetAppsRequest request = new GetAppsRequest(orgId);

        return request;
    }

    public GetAppsResponse call() throws Exception {
        
        RequestOperation<GetAppsRequest, GetAppsResponse> operation
              = new GetApps.Sync(sdkConfiguration);
        GetAppsRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
