/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.hathora.cloud_sdk.models.operations;

import dev.hathora.cloud_sdk.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class GetConnectionInfoDeprecatedRequestBuilder {

    private Optional<String> appId = Optional.empty();
    private String roomId;
    private final SDKMethodInterfaces.MethodCallGetConnectionInfoDeprecated sdk;

    public GetConnectionInfoDeprecatedRequestBuilder(SDKMethodInterfaces.MethodCallGetConnectionInfoDeprecated sdk) {
        this.sdk = sdk;
    }
                
    public GetConnectionInfoDeprecatedRequestBuilder appId(java.lang.String appId) {
        Utils.checkNotNull(appId, "appId");
        this.appId = Optional.of(appId);
        return this;
    }

    public GetConnectionInfoDeprecatedRequestBuilder appId(java.util.Optional<java.lang.String> appId) {
        Utils.checkNotNull(appId, "appId");
        this.appId = appId;
        return this;
    }

    public GetConnectionInfoDeprecatedRequestBuilder roomId(java.lang.String roomId) {
        Utils.checkNotNull(roomId, "roomId");
        this.roomId = roomId;
        return this;
    }

    public GetConnectionInfoDeprecatedResponse call() throws Exception {

        return sdk.getConnectionInfoDeprecated(
            appId,
            roomId);
    }
}
