/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.hathora.cloud_sdk.models.shared.FleetMetricsData;
import dev.hathora.cloud_sdk.utils.Response;
import dev.hathora.cloud_sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class GetFleetMetricsDeprecatedResponse implements Response {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * Ok
     */
    private Optional<? extends FleetMetricsData> fleetMetricsData;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    @JsonCreator
    public GetFleetMetricsDeprecatedResponse(
            String contentType,
            Optional<? extends FleetMetricsData> fleetMetricsData,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(fleetMetricsData, "fleetMetricsData");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.contentType = contentType;
        this.fleetMetricsData = fleetMetricsData;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
    }
    
    public GetFleetMetricsDeprecatedResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, Optional.empty(), statusCode,
            rawResponse);
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * Ok
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<FleetMetricsData> fleetMetricsData() {
        return (Optional<FleetMetricsData>) fleetMetricsData;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public GetFleetMetricsDeprecatedResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * Ok
     */
    public GetFleetMetricsDeprecatedResponse withFleetMetricsData(FleetMetricsData fleetMetricsData) {
        Utils.checkNotNull(fleetMetricsData, "fleetMetricsData");
        this.fleetMetricsData = Optional.ofNullable(fleetMetricsData);
        return this;
    }


    /**
     * Ok
     */
    public GetFleetMetricsDeprecatedResponse withFleetMetricsData(Optional<? extends FleetMetricsData> fleetMetricsData) {
        Utils.checkNotNull(fleetMetricsData, "fleetMetricsData");
        this.fleetMetricsData = fleetMetricsData;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public GetFleetMetricsDeprecatedResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetFleetMetricsDeprecatedResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetFleetMetricsDeprecatedResponse other = (GetFleetMetricsDeprecatedResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.fleetMetricsData, other.fleetMetricsData) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, fleetMetricsData, statusCode,
            rawResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetFleetMetricsDeprecatedResponse.class,
                "contentType", contentType,
                "fleetMetricsData", fleetMetricsData,
                "statusCode", statusCode,
                "rawResponse", rawResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Optional<? extends FleetMetricsData> fleetMetricsData = Optional.empty();

        private Integer statusCode;

        private HttpResponse<InputStream> rawResponse;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * Ok
         */
        public Builder fleetMetricsData(FleetMetricsData fleetMetricsData) {
            Utils.checkNotNull(fleetMetricsData, "fleetMetricsData");
            this.fleetMetricsData = Optional.ofNullable(fleetMetricsData);
            return this;
        }

        /**
         * Ok
         */
        public Builder fleetMetricsData(Optional<? extends FleetMetricsData> fleetMetricsData) {
            Utils.checkNotNull(fleetMetricsData, "fleetMetricsData");
            this.fleetMetricsData = fleetMetricsData;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        public GetFleetMetricsDeprecatedResponse build() {

            return new GetFleetMetricsDeprecatedResponse(
                contentType, fleetMetricsData, statusCode,
                rawResponse);
        }

    }
}
