/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations;

import static dev.hathora.cloud_sdk.operations.Operations.RequestOperation;

import dev.hathora.cloud_sdk.SDKConfiguration;
import dev.hathora.cloud_sdk.operations.GetFleetRegionMetricsDeprecated;
import dev.hathora.cloud_sdk.utils.Headers;
import dev.hathora.cloud_sdk.utils.Utils;

public class GetFleetRegionMetricsDeprecatedRequestBuilder {

    private GetFleetRegionMetricsDeprecatedRequest request;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetFleetRegionMetricsDeprecatedRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetFleetRegionMetricsDeprecatedRequestBuilder request(GetFleetRegionMetricsDeprecatedRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetFleetRegionMetricsDeprecatedResponse call() {
        
        RequestOperation<GetFleetRegionMetricsDeprecatedRequest, GetFleetRegionMetricsDeprecatedResponse> operation
              = new GetFleetRegionMetricsDeprecated.Sync(sdkConfiguration, _headers);

        return operation.handleResponse(operation.doRequest(request));
    }
}
