/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations;

import static dev.hathora.cloud_sdk.operations.Operations.RequestOperation;

import dev.hathora.cloud_sdk.SDKConfiguration;
import dev.hathora.cloud_sdk.operations.GetInactiveRoomsForProcessDeprecated;
import dev.hathora.cloud_sdk.utils.Headers;
import dev.hathora.cloud_sdk.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class GetInactiveRoomsForProcessDeprecatedRequestBuilder {

    private Optional<String> appId = Optional.empty();
    private String processId;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetInactiveRoomsForProcessDeprecatedRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public GetInactiveRoomsForProcessDeprecatedRequestBuilder appId(String appId) {
        Utils.checkNotNull(appId, "appId");
        this.appId = Optional.of(appId);
        return this;
    }

    public GetInactiveRoomsForProcessDeprecatedRequestBuilder appId(Optional<String> appId) {
        Utils.checkNotNull(appId, "appId");
        this.appId = appId;
        return this;
    }

    public GetInactiveRoomsForProcessDeprecatedRequestBuilder processId(String processId) {
        Utils.checkNotNull(processId, "processId");
        this.processId = processId;
        return this;
    }


    private GetInactiveRoomsForProcessDeprecatedRequest buildRequest() {

        GetInactiveRoomsForProcessDeprecatedRequest request = new GetInactiveRoomsForProcessDeprecatedRequest(appId,
            processId);

        return request;
    }

    public GetInactiveRoomsForProcessDeprecatedResponse call() {
        
        RequestOperation<GetInactiveRoomsForProcessDeprecatedRequest, GetInactiveRoomsForProcessDeprecatedResponse> operation
              = new GetInactiveRoomsForProcessDeprecated.Sync(sdkConfiguration, _headers);
        GetInactiveRoomsForProcessDeprecatedRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
