/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations;

import static dev.hathora.cloud_sdk.operations.Operations.RequestOperation;

import dev.hathora.cloud_sdk.SDKConfiguration;
import dev.hathora.cloud_sdk.operations.GetInactiveRoomsForProcess;
import dev.hathora.cloud_sdk.utils.Headers;
import dev.hathora.cloud_sdk.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class GetInactiveRoomsForProcessRequestBuilder {

    private Optional<String> appId = Optional.empty();
    private String processId;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetInactiveRoomsForProcessRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public GetInactiveRoomsForProcessRequestBuilder appId(String appId) {
        Utils.checkNotNull(appId, "appId");
        this.appId = Optional.of(appId);
        return this;
    }

    public GetInactiveRoomsForProcessRequestBuilder appId(Optional<String> appId) {
        Utils.checkNotNull(appId, "appId");
        this.appId = appId;
        return this;
    }

    public GetInactiveRoomsForProcessRequestBuilder processId(String processId) {
        Utils.checkNotNull(processId, "processId");
        this.processId = processId;
        return this;
    }


    private GetInactiveRoomsForProcessRequest buildRequest() {

        GetInactiveRoomsForProcessRequest request = new GetInactiveRoomsForProcessRequest(appId,
            processId);

        return request;
    }

    public GetInactiveRoomsForProcessResponse call() {
        
        RequestOperation<GetInactiveRoomsForProcessRequest, GetInactiveRoomsForProcessResponse> operation
              = new GetInactiveRoomsForProcess.Sync(sdkConfiguration, _headers);
        GetInactiveRoomsForProcessRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
