/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations;

import static dev.hathora.cloud_sdk.operations.Operations.RequestOperation;

import dev.hathora.cloud_sdk.SDKConfiguration;
import dev.hathora.cloud_sdk.operations.GetLobbyInfoByShortCode;
import dev.hathora.cloud_sdk.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import java.util.Optional;

public class GetLobbyInfoByShortCodeRequestBuilder {

    private Optional<String> appId = Optional.empty();
    private String shortCode;
    private final SDKConfiguration sdkConfiguration;

    public GetLobbyInfoByShortCodeRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public GetLobbyInfoByShortCodeRequestBuilder appId(String appId) {
        Utils.checkNotNull(appId, "appId");
        this.appId = Optional.of(appId);
        return this;
    }

    public GetLobbyInfoByShortCodeRequestBuilder appId(Optional<String> appId) {
        Utils.checkNotNull(appId, "appId");
        this.appId = appId;
        return this;
    }

    public GetLobbyInfoByShortCodeRequestBuilder shortCode(String shortCode) {
        Utils.checkNotNull(shortCode, "shortCode");
        this.shortCode = shortCode;
        return this;
    }


    private GetLobbyInfoByShortCodeRequest buildRequest() {

        GetLobbyInfoByShortCodeRequest request = new GetLobbyInfoByShortCodeRequest(appId,
            shortCode);

        return request;
    }

    public GetLobbyInfoByShortCodeResponse call() throws Exception {
        
        RequestOperation<GetLobbyInfoByShortCodeRequest, GetLobbyInfoByShortCodeResponse> operation
              = new GetLobbyInfoByShortCode.Sync(sdkConfiguration);
        GetLobbyInfoByShortCodeRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
