/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations;

import static dev.hathora.cloud_sdk.operations.Operations.RequestOperation;

import dev.hathora.cloud_sdk.SDKConfiguration;
import dev.hathora.cloud_sdk.operations.GetOrgMembers;
import dev.hathora.cloud_sdk.utils.Headers;
import dev.hathora.cloud_sdk.utils.Utils;
import java.lang.String;

public class GetOrgMembersRequestBuilder {

    private String orgId;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetOrgMembersRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetOrgMembersRequestBuilder orgId(String orgId) {
        Utils.checkNotNull(orgId, "orgId");
        this.orgId = orgId;
        return this;
    }


    private GetOrgMembersRequest buildRequest() {

        GetOrgMembersRequest request = new GetOrgMembersRequest(orgId);

        return request;
    }

    public GetOrgMembersResponse call() {
        
        RequestOperation<GetOrgMembersRequest, GetOrgMembersResponse> operation
              = new GetOrgMembers.Sync(sdkConfiguration, _headers);
        GetOrgMembersRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
