/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations;

import static dev.hathora.cloud_sdk.operations.Operations.RequestlessOperation;

import dev.hathora.cloud_sdk.SDKConfiguration;
import dev.hathora.cloud_sdk.operations.GetPingServiceEndpoints;
import java.lang.Exception;

public class GetPingServiceEndpointsRequestBuilder {

    private final SDKConfiguration sdkConfiguration;

    public GetPingServiceEndpointsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetPingServiceEndpointsResponse call() throws Exception {
        
        RequestlessOperation<GetPingServiceEndpointsResponse> operation
            = new GetPingServiceEndpoints.Sync(sdkConfiguration);

        return operation.handleResponse(operation.doRequest());
    }
}
