/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.hathora.cloud_sdk.models.shared.Region;
import dev.hathora.cloud_sdk.utils.SpeakeasyMetadata;
import dev.hathora.cloud_sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class ListProvisionedNodesRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=fleetId")
    private String fleetId;


    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=orgId")
    private Optional<String> orgId;


    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=region")
    private Optional<? extends Region> region;

    @JsonCreator
    public ListProvisionedNodesRequest(
            String fleetId,
            Optional<String> orgId,
            Optional<? extends Region> region) {
        Utils.checkNotNull(fleetId, "fleetId");
        Utils.checkNotNull(orgId, "orgId");
        Utils.checkNotNull(region, "region");
        this.fleetId = fleetId;
        this.orgId = orgId;
        this.region = region;
    }
    
    public ListProvisionedNodesRequest(
            String fleetId) {
        this(fleetId, Optional.empty(), Optional.empty());
    }

    @JsonIgnore
    public String fleetId() {
        return fleetId;
    }

    @JsonIgnore
    public Optional<String> orgId() {
        return orgId;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Region> region() {
        return (Optional<Region>) region;
    }

    public static Builder builder() {
        return new Builder();
    }


    public ListProvisionedNodesRequest withFleetId(String fleetId) {
        Utils.checkNotNull(fleetId, "fleetId");
        this.fleetId = fleetId;
        return this;
    }

    public ListProvisionedNodesRequest withOrgId(String orgId) {
        Utils.checkNotNull(orgId, "orgId");
        this.orgId = Optional.ofNullable(orgId);
        return this;
    }


    public ListProvisionedNodesRequest withOrgId(Optional<String> orgId) {
        Utils.checkNotNull(orgId, "orgId");
        this.orgId = orgId;
        return this;
    }

    public ListProvisionedNodesRequest withRegion(Region region) {
        Utils.checkNotNull(region, "region");
        this.region = Optional.ofNullable(region);
        return this;
    }


    public ListProvisionedNodesRequest withRegion(Optional<? extends Region> region) {
        Utils.checkNotNull(region, "region");
        this.region = region;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListProvisionedNodesRequest other = (ListProvisionedNodesRequest) o;
        return 
            Utils.enhancedDeepEquals(this.fleetId, other.fleetId) &&
            Utils.enhancedDeepEquals(this.orgId, other.orgId) &&
            Utils.enhancedDeepEquals(this.region, other.region);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            fleetId, orgId, region);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListProvisionedNodesRequest.class,
                "fleetId", fleetId,
                "orgId", orgId,
                "region", region);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String fleetId;

        private Optional<String> orgId = Optional.empty();

        private Optional<? extends Region> region = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder fleetId(String fleetId) {
            Utils.checkNotNull(fleetId, "fleetId");
            this.fleetId = fleetId;
            return this;
        }


        public Builder orgId(String orgId) {
            Utils.checkNotNull(orgId, "orgId");
            this.orgId = Optional.ofNullable(orgId);
            return this;
        }

        public Builder orgId(Optional<String> orgId) {
            Utils.checkNotNull(orgId, "orgId");
            this.orgId = orgId;
            return this;
        }


        public Builder region(Region region) {
            Utils.checkNotNull(region, "region");
            this.region = Optional.ofNullable(region);
            return this;
        }

        public Builder region(Optional<? extends Region> region) {
            Utils.checkNotNull(region, "region");
            this.region = region;
            return this;
        }

        public ListProvisionedNodesRequest build() {

            return new ListProvisionedNodesRequest(
                fleetId, orgId, region);
        }

    }
}
