/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations;

import static dev.hathora.cloud_sdk.operations.Operations.RequestOperation;

import dev.hathora.cloud_sdk.SDKConfiguration;
import dev.hathora.cloud_sdk.models.shared.RescindUserInvite;
import dev.hathora.cloud_sdk.operations.RescindInvite;
import dev.hathora.cloud_sdk.utils.Utils;
import java.lang.Exception;
import java.lang.String;

public class RescindInviteRequestBuilder {

    private RescindUserInvite rescindUserInvite;
    private String orgId;
    private final SDKConfiguration sdkConfiguration;

    public RescindInviteRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public RescindInviteRequestBuilder rescindUserInvite(RescindUserInvite rescindUserInvite) {
        Utils.checkNotNull(rescindUserInvite, "rescindUserInvite");
        this.rescindUserInvite = rescindUserInvite;
        return this;
    }

    public RescindInviteRequestBuilder orgId(String orgId) {
        Utils.checkNotNull(orgId, "orgId");
        this.orgId = orgId;
        return this;
    }


    private RescindInviteRequest buildRequest() {

        RescindInviteRequest request = new RescindInviteRequest(rescindUserInvite,
            orgId);

        return request;
    }

    public RescindInviteResponse call() throws Exception {
        
        RequestOperation<RescindInviteRequest, RescindInviteResponse> operation
              = new RescindInvite.Sync(sdkConfiguration);
        RescindInviteRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
