/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package dev.hathora.cloud_api.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class DeleteAppResponse {
    
    public String contentType;

    public DeleteAppResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public String deleteApp404ApplicationJSONString;

    public DeleteAppResponse withDeleteApp404ApplicationJSONString(String deleteApp404ApplicationJSONString) {
        this.deleteApp404ApplicationJSONString = deleteApp404ApplicationJSONString;
        return this;
    }
    
    
    public String deleteApp500ApplicationJSONString;

    public DeleteAppResponse withDeleteApp500ApplicationJSONString(String deleteApp500ApplicationJSONString) {
        this.deleteApp500ApplicationJSONString = deleteApp500ApplicationJSONString;
        return this;
    }
    
    
    public Integer statusCode;

    public DeleteAppResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public DeleteAppResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public DeleteAppResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
