/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package dev.hathora.cloud_api.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import dev.hathora.cloud_api.utils.SpeakeasyMetadata;


public class DeleteBuildRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=appId")
    public String appId;

    public DeleteBuildRequest withAppId(String appId) {
        this.appId = appId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=buildId")
    public Integer buildId;

    public DeleteBuildRequest withBuildId(Integer buildId) {
        this.buildId = buildId;
        return this;
    }
    
    public DeleteBuildRequest(@JsonProperty("appId") String appId, @JsonProperty("buildId") Integer buildId) {
        this.appId = appId;
        this.buildId = buildId;
  }
}
