/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package dev.hathora.cloud_api.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetActiveRoomsForProcessDeprecatedResponse {
    
    public String contentType;

    public GetActiveRoomsForProcessDeprecatedResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public String getActiveRoomsForProcessDeprecated404ApplicationJSONString;

    public GetActiveRoomsForProcessDeprecatedResponse withGetActiveRoomsForProcessDeprecated404ApplicationJSONString(String getActiveRoomsForProcessDeprecated404ApplicationJSONString) {
        this.getActiveRoomsForProcessDeprecated404ApplicationJSONString = getActiveRoomsForProcessDeprecated404ApplicationJSONString;
        return this;
    }
    
    /**
     * Ok
     */
    
    public dev.hathora.cloud_api.models.shared.RoomWithoutAllocations[] roomWithoutAllocations;

    public GetActiveRoomsForProcessDeprecatedResponse withRoomWithoutAllocations(dev.hathora.cloud_api.models.shared.RoomWithoutAllocations[] roomWithoutAllocations) {
        this.roomWithoutAllocations = roomWithoutAllocations;
        return this;
    }
    
    
    public Integer statusCode;

    public GetActiveRoomsForProcessDeprecatedResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetActiveRoomsForProcessDeprecatedResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetActiveRoomsForProcessDeprecatedResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
