/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations.async;

import static dev.hathora.cloud_sdk.operations.Operations.AsyncRequestOperation;

import dev.hathora.cloud_sdk.SDKConfiguration;
import dev.hathora.cloud_sdk.models.operations.AcceptInviteRequest;
import dev.hathora.cloud_sdk.operations.AcceptInvite;
import dev.hathora.cloud_sdk.utils.Headers;
import dev.hathora.cloud_sdk.utils.Utils;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class AcceptInviteRequestBuilder {

    private String orgId;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public AcceptInviteRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public AcceptInviteRequestBuilder orgId(String orgId) {
        Utils.checkNotNull(orgId, "orgId");
        this.orgId = orgId;
        return this;
    }


    private AcceptInviteRequest buildRequest() {

        AcceptInviteRequest request = new AcceptInviteRequest(orgId);

        return request;
    }

    public CompletableFuture<AcceptInviteResponse> call() {
        
        AsyncRequestOperation<AcceptInviteRequest, AcceptInviteResponse> operation
              = new AcceptInvite.Async(sdkConfiguration, _headers);
        AcceptInviteRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
