/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations.async;

import static dev.hathora.cloud_sdk.operations.Operations.AsyncRequestOperation;

import dev.hathora.cloud_sdk.SDKConfiguration;
import dev.hathora.cloud_sdk.models.operations.CreateBuildDeprecatedRequest;
import dev.hathora.cloud_sdk.models.shared.CreateBuildParams;
import dev.hathora.cloud_sdk.operations.CreateBuildDeprecated;
import dev.hathora.cloud_sdk.utils.Headers;
import dev.hathora.cloud_sdk.utils.Utils;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class CreateBuildDeprecatedRequestBuilder {

    private CreateBuildParams createBuildParams;
    private Optional<String> appId = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public CreateBuildDeprecatedRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public CreateBuildDeprecatedRequestBuilder createBuildParams(CreateBuildParams createBuildParams) {
        Utils.checkNotNull(createBuildParams, "createBuildParams");
        this.createBuildParams = createBuildParams;
        return this;
    }
                
    public CreateBuildDeprecatedRequestBuilder appId(String appId) {
        Utils.checkNotNull(appId, "appId");
        this.appId = Optional.of(appId);
        return this;
    }

    public CreateBuildDeprecatedRequestBuilder appId(Optional<String> appId) {
        Utils.checkNotNull(appId, "appId");
        this.appId = appId;
        return this;
    }


    private CreateBuildDeprecatedRequest buildRequest() {

        CreateBuildDeprecatedRequest request = new CreateBuildDeprecatedRequest(createBuildParams,
            appId);

        return request;
    }

    public CompletableFuture<CreateBuildDeprecatedResponse> call() {
        
        AsyncRequestOperation<CreateBuildDeprecatedRequest, CreateBuildDeprecatedResponse> operation
              = new CreateBuildDeprecated.Async(sdkConfiguration, _headers);
        CreateBuildDeprecatedRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
