/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations.async;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.hathora.cloud_sdk.models.shared.BuildWithUploadUrl;
import dev.hathora.cloud_sdk.utils.AsyncResponse;
import dev.hathora.cloud_sdk.utils.Blob;
import dev.hathora.cloud_sdk.utils.Utils;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class CreateBuildWithUploadUrlV2DeprecatedResponse implements AsyncResponse {

    private Optional<? extends BuildWithUploadUrl> buildWithUploadUrl;

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    @JsonCreator
    public CreateBuildWithUploadUrlV2DeprecatedResponse(
            Optional<? extends BuildWithUploadUrl> buildWithUploadUrl,
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse) {
        Utils.checkNotNull(buildWithUploadUrl, "buildWithUploadUrl");
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.buildWithUploadUrl = buildWithUploadUrl;
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
    }
    
    public CreateBuildWithUploadUrlV2DeprecatedResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse) {
        this(Optional.empty(), contentType, statusCode,
            rawResponse);
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<BuildWithUploadUrl> buildWithUploadUrl() {
        return (Optional<BuildWithUploadUrl>) buildWithUploadUrl;
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<Blob> rawResponse() {
        return rawResponse;
    }

    public static Builder builder() {
        return new Builder();
    }


    public CreateBuildWithUploadUrlV2DeprecatedResponse withBuildWithUploadUrl(BuildWithUploadUrl buildWithUploadUrl) {
        Utils.checkNotNull(buildWithUploadUrl, "buildWithUploadUrl");
        this.buildWithUploadUrl = Optional.ofNullable(buildWithUploadUrl);
        return this;
    }


    public CreateBuildWithUploadUrlV2DeprecatedResponse withBuildWithUploadUrl(Optional<? extends BuildWithUploadUrl> buildWithUploadUrl) {
        Utils.checkNotNull(buildWithUploadUrl, "buildWithUploadUrl");
        this.buildWithUploadUrl = buildWithUploadUrl;
        return this;
    }

    /**
     * HTTP response content type for this operation
     */
    public CreateBuildWithUploadUrlV2DeprecatedResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public CreateBuildWithUploadUrlV2DeprecatedResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public CreateBuildWithUploadUrlV2DeprecatedResponse withRawResponse(HttpResponse<Blob> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateBuildWithUploadUrlV2DeprecatedResponse other = (CreateBuildWithUploadUrlV2DeprecatedResponse) o;
        return 
            Utils.enhancedDeepEquals(this.buildWithUploadUrl, other.buildWithUploadUrl) &&
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            buildWithUploadUrl, contentType, statusCode,
            rawResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateBuildWithUploadUrlV2DeprecatedResponse.class,
                "buildWithUploadUrl", buildWithUploadUrl,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends BuildWithUploadUrl> buildWithUploadUrl = Optional.empty();

        private String contentType;

        private Integer statusCode;

        private HttpResponse<Blob> rawResponse;

        private Builder() {
          // force use of static builder() method
        }


        public Builder buildWithUploadUrl(BuildWithUploadUrl buildWithUploadUrl) {
            Utils.checkNotNull(buildWithUploadUrl, "buildWithUploadUrl");
            this.buildWithUploadUrl = Optional.ofNullable(buildWithUploadUrl);
            return this;
        }

        public Builder buildWithUploadUrl(Optional<? extends BuildWithUploadUrl> buildWithUploadUrl) {
            Utils.checkNotNull(buildWithUploadUrl, "buildWithUploadUrl");
            this.buildWithUploadUrl = buildWithUploadUrl;
            return this;
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<Blob> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        public CreateBuildWithUploadUrlV2DeprecatedResponse build() {

            return new CreateBuildWithUploadUrlV2DeprecatedResponse(
                buildWithUploadUrl, contentType, statusCode,
                rawResponse);
        }

    }
}
