/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations.async;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.hathora.cloud_sdk.models.shared.DeploymentsV3Page;
import dev.hathora.cloud_sdk.utils.AsyncResponse;
import dev.hathora.cloud_sdk.utils.Blob;
import dev.hathora.cloud_sdk.utils.Utils;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class GetDeploymentsResponse implements AsyncResponse {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * Ok
     */
    private Optional<? extends DeploymentsV3Page> deploymentsV3Page;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    @JsonCreator
    public GetDeploymentsResponse(
            String contentType,
            Optional<? extends DeploymentsV3Page> deploymentsV3Page,
            int statusCode,
            HttpResponse<Blob> rawResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(deploymentsV3Page, "deploymentsV3Page");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.contentType = contentType;
        this.deploymentsV3Page = deploymentsV3Page;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
    }
    
    public GetDeploymentsResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse) {
        this(contentType, Optional.empty(), statusCode,
            rawResponse);
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * Ok
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<DeploymentsV3Page> deploymentsV3Page() {
        return (Optional<DeploymentsV3Page>) deploymentsV3Page;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<Blob> rawResponse() {
        return rawResponse;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public GetDeploymentsResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * Ok
     */
    public GetDeploymentsResponse withDeploymentsV3Page(DeploymentsV3Page deploymentsV3Page) {
        Utils.checkNotNull(deploymentsV3Page, "deploymentsV3Page");
        this.deploymentsV3Page = Optional.ofNullable(deploymentsV3Page);
        return this;
    }


    /**
     * Ok
     */
    public GetDeploymentsResponse withDeploymentsV3Page(Optional<? extends DeploymentsV3Page> deploymentsV3Page) {
        Utils.checkNotNull(deploymentsV3Page, "deploymentsV3Page");
        this.deploymentsV3Page = deploymentsV3Page;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public GetDeploymentsResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetDeploymentsResponse withRawResponse(HttpResponse<Blob> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetDeploymentsResponse other = (GetDeploymentsResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.deploymentsV3Page, other.deploymentsV3Page) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, deploymentsV3Page, statusCode,
            rawResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetDeploymentsResponse.class,
                "contentType", contentType,
                "deploymentsV3Page", deploymentsV3Page,
                "statusCode", statusCode,
                "rawResponse", rawResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Optional<? extends DeploymentsV3Page> deploymentsV3Page = Optional.empty();

        private Integer statusCode;

        private HttpResponse<Blob> rawResponse;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * Ok
         */
        public Builder deploymentsV3Page(DeploymentsV3Page deploymentsV3Page) {
            Utils.checkNotNull(deploymentsV3Page, "deploymentsV3Page");
            this.deploymentsV3Page = Optional.ofNullable(deploymentsV3Page);
            return this;
        }

        /**
         * Ok
         */
        public Builder deploymentsV3Page(Optional<? extends DeploymentsV3Page> deploymentsV3Page) {
            Utils.checkNotNull(deploymentsV3Page, "deploymentsV3Page");
            this.deploymentsV3Page = deploymentsV3Page;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<Blob> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        public GetDeploymentsResponse build() {

            return new GetDeploymentsResponse(
                contentType, deploymentsV3Page, statusCode,
                rawResponse);
        }

    }
}
