/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations.async;

import static dev.hathora.cloud_sdk.operations.Operations.AsyncRequestOperation;

import dev.hathora.cloud_sdk.SDKConfiguration;
import dev.hathora.cloud_sdk.models.operations.GetLatestDeploymentRequest;
import dev.hathora.cloud_sdk.operations.GetLatestDeployment;
import dev.hathora.cloud_sdk.utils.Headers;
import dev.hathora.cloud_sdk.utils.Utils;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class GetLatestDeploymentRequestBuilder {

    private Optional<String> appId = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetLatestDeploymentRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public GetLatestDeploymentRequestBuilder appId(String appId) {
        Utils.checkNotNull(appId, "appId");
        this.appId = Optional.of(appId);
        return this;
    }

    public GetLatestDeploymentRequestBuilder appId(Optional<String> appId) {
        Utils.checkNotNull(appId, "appId");
        this.appId = appId;
        return this;
    }


    private GetLatestDeploymentRequest buildRequest() {

        GetLatestDeploymentRequest request = new GetLatestDeploymentRequest(appId);

        return request;
    }

    public CompletableFuture<GetLatestDeploymentResponse> call() {
        
        AsyncRequestOperation<GetLatestDeploymentRequest, GetLatestDeploymentResponse> operation
              = new GetLatestDeployment.Async(sdkConfiguration, _headers);
        GetLatestDeploymentRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
