/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations.async;

import static dev.hathora.cloud_sdk.operations.Operations.AsyncRequestlessOperation;

import dev.hathora.cloud_sdk.SDKConfiguration;
import dev.hathora.cloud_sdk.operations.GetOrgs;
import java.lang.Exception;
import java.util.concurrent.CompletableFuture;

public class GetOrgsRequestBuilder {

    private final SDKConfiguration sdkConfiguration;

    public GetOrgsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public CompletableFuture<GetOrgsResponse> call() throws Exception {
        
        AsyncRequestlessOperation<GetOrgsResponse> operation
            = new GetOrgs.Async(sdkConfiguration);

        return operation.doRequest()
            .thenCompose(operation::handleResponse);
    }
}
