/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations.async;

import static dev.hathora.cloud_sdk.operations.Operations.AsyncRequestlessOperation;

import dev.hathora.cloud_sdk.SDKConfiguration;
import dev.hathora.cloud_sdk.operations.GetPingServiceEndpoints;
import java.lang.Exception;
import java.util.concurrent.CompletableFuture;

public class GetPingServiceEndpointsRequestBuilder {

    private final SDKConfiguration sdkConfiguration;

    public GetPingServiceEndpointsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public CompletableFuture<GetPingServiceEndpointsResponse> call() throws Exception {
        
        AsyncRequestlessOperation<GetPingServiceEndpointsResponse> operation
            = new GetPingServiceEndpoints.Async(sdkConfiguration);

        return operation.doRequest()
            .thenCompose(operation::handleResponse);
    }
}
