/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations.async;

import static dev.hathora.cloud_sdk.operations.Operations.AsyncRequestOperation;

import dev.hathora.cloud_sdk.SDKConfiguration;
import dev.hathora.cloud_sdk.models.shared.VerificationEmailRequest;
import dev.hathora.cloud_sdk.operations.SendVerificationEmail;
import dev.hathora.cloud_sdk.utils.Headers;
import dev.hathora.cloud_sdk.utils.Utils;
import java.util.concurrent.CompletableFuture;

public class SendVerificationEmailRequestBuilder {

    private VerificationEmailRequest request;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public SendVerificationEmailRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public SendVerificationEmailRequestBuilder request(VerificationEmailRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompletableFuture<SendVerificationEmailResponse> call() {
        
        AsyncRequestOperation<VerificationEmailRequest, SendVerificationEmailResponse> operation
              = new SendVerificationEmail.Async(sdkConfiguration, _headers);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
