/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk.models.operations.async;

import static dev.hathora.cloud_sdk.operations.Operations.AsyncRequestOperation;

import dev.hathora.cloud_sdk.SDKConfiguration;
import dev.hathora.cloud_sdk.models.operations.StopProcessV2DeprecatedRequest;
import dev.hathora.cloud_sdk.operations.StopProcessV2Deprecated;
import dev.hathora.cloud_sdk.utils.Headers;
import dev.hathora.cloud_sdk.utils.Utils;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class StopProcessV2DeprecatedRequestBuilder {

    private Optional<String> appId = Optional.empty();
    private String processId;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public StopProcessV2DeprecatedRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public StopProcessV2DeprecatedRequestBuilder appId(String appId) {
        Utils.checkNotNull(appId, "appId");
        this.appId = Optional.of(appId);
        return this;
    }

    public StopProcessV2DeprecatedRequestBuilder appId(Optional<String> appId) {
        Utils.checkNotNull(appId, "appId");
        this.appId = appId;
        return this;
    }

    public StopProcessV2DeprecatedRequestBuilder processId(String processId) {
        Utils.checkNotNull(processId, "processId");
        this.processId = processId;
        return this;
    }


    private StopProcessV2DeprecatedRequest buildRequest() {

        StopProcessV2DeprecatedRequest request = new StopProcessV2DeprecatedRequest(appId,
            processId);

        return request;
    }

    public CompletableFuture<StopProcessV2DeprecatedResponse> call() {
        
        AsyncRequestOperation<StopProcessV2DeprecatedRequest, StopProcessV2DeprecatedResponse> operation
              = new StopProcessV2Deprecated.Async(sdkConfiguration, _headers);
        StopProcessV2DeprecatedRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
