/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk;

import static dev.hathora.cloud_sdk.operations.Operations.AsyncRequestlessOperation;

import dev.hathora.cloud_sdk.models.operations.async.GetPingServiceEndpointsRequestBuilder;
import dev.hathora.cloud_sdk.models.operations.async.GetPingServiceEndpointsResponse;
import dev.hathora.cloud_sdk.operations.GetPingServiceEndpoints;
import dev.hathora.cloud_sdk.utils.Headers;
import java.util.concurrent.CompletableFuture;

/**
 * Service that allows clients to directly ping all Hathora regions to get latency information
 */
public class AsyncDiscoveryV2 {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final DiscoveryV2 syncSDK;

    AsyncDiscoveryV2(DiscoveryV2 syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public DiscoveryV2 sync() {
        return syncSDK;
    }


    /**
     * GetPingServiceEndpoints
     * 
     * <p>Returns an array of all regions with a host and port that a client can directly ping. Open a
     * websocket connection to `wss://&lt;host&gt;:<port>/ws` and send a packet. To calculate ping, measure
     * the time it takes to get an echo packet back.
     * 
     * @return The async call builder
     */
    public GetPingServiceEndpointsRequestBuilder getPingServiceEndpoints() {
        return new GetPingServiceEndpointsRequestBuilder(sdkConfiguration);
    }

    /**
     * GetPingServiceEndpoints
     * 
     * <p>Returns an array of all regions with a host and port that a client can directly ping. Open a
     * websocket connection to `wss://&lt;host&gt;:<port>/ws` and send a packet. To calculate ping, measure
     * the time it takes to get an echo packet back.
     * 
     * @return {@code CompletableFuture<GetPingServiceEndpointsResponse>} - The async response
     */
    public CompletableFuture<GetPingServiceEndpointsResponse> getPingServiceEndpointsDirect() {
        AsyncRequestlessOperation<GetPingServiceEndpointsResponse> operation
            = new GetPingServiceEndpoints.Async(sdkConfiguration, _headers);
        return operation.doRequest()
            .thenCompose(operation::handleResponse);
    }

}
