/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk;

import static dev.hathora.cloud_sdk.operations.Operations.RequestOperation;

import dev.hathora.cloud_sdk.models.operations.LoginAnonymousRequest;
import dev.hathora.cloud_sdk.models.operations.LoginAnonymousRequestBuilder;
import dev.hathora.cloud_sdk.models.operations.LoginAnonymousResponse;
import dev.hathora.cloud_sdk.models.operations.LoginGoogleRequest;
import dev.hathora.cloud_sdk.models.operations.LoginGoogleRequestBuilder;
import dev.hathora.cloud_sdk.models.operations.LoginGoogleResponse;
import dev.hathora.cloud_sdk.models.operations.LoginNicknameRequest;
import dev.hathora.cloud_sdk.models.operations.LoginNicknameRequestBuilder;
import dev.hathora.cloud_sdk.models.operations.LoginNicknameResponse;
import dev.hathora.cloud_sdk.models.shared.GoogleIdTokenObject;
import dev.hathora.cloud_sdk.models.shared.NicknameObject;
import dev.hathora.cloud_sdk.operations.LoginAnonymous;
import dev.hathora.cloud_sdk.operations.LoginGoogle;
import dev.hathora.cloud_sdk.operations.LoginNickname;
import dev.hathora.cloud_sdk.utils.Headers;
import java.lang.String;
import java.util.Optional;

/**
 * Operations that allow you to generate a Hathora-signed [JSON web token (JWT)](https://jwt.io/) for
 * [player authentication](https://hathora.dev/docs/lobbies-and-matchmaking/auth-service).
 */
public class AuthV1 {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncAuthV1 asyncSDK;

    AuthV1(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncAuthV1(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncAuthV1 async() {
        return asyncSDK;
    }

    /**
     * LoginAnonymous
     * 
     * <p>Returns a unique player token for an anonymous user.
     * 
     * @return The call builder
     */
    public LoginAnonymousRequestBuilder loginAnonymous() {
        return new LoginAnonymousRequestBuilder(sdkConfiguration);
    }

    /**
     * LoginAnonymous
     * 
     * <p>Returns a unique player token for an anonymous user.
     * 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LoginAnonymousResponse loginAnonymousDirect() {
        return loginAnonymous(Optional.empty());
    }

    /**
     * LoginAnonymous
     * 
     * <p>Returns a unique player token for an anonymous user.
     * 
     * @param appId 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LoginAnonymousResponse loginAnonymous(Optional<String> appId) {
        LoginAnonymousRequest request =
            LoginAnonymousRequest
                .builder()
                .appId(appId)
                .build();
        RequestOperation<LoginAnonymousRequest, LoginAnonymousResponse> operation
              = new LoginAnonymous.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * LoginGoogle
     * 
     * <p>Returns a unique player token using a Google-signed OIDC `idToken`.
     * 
     * @return The call builder
     */
    public LoginGoogleRequestBuilder loginGoogle() {
        return new LoginGoogleRequestBuilder(sdkConfiguration);
    }

    /**
     * LoginGoogle
     * 
     * <p>Returns a unique player token using a Google-signed OIDC `idToken`.
     * 
     * @param googleIdTokenObject 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LoginGoogleResponse loginGoogle(GoogleIdTokenObject googleIdTokenObject) {
        return loginGoogle(googleIdTokenObject, Optional.empty());
    }

    /**
     * LoginGoogle
     * 
     * <p>Returns a unique player token using a Google-signed OIDC `idToken`.
     * 
     * @param googleIdTokenObject 
     * @param appId 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LoginGoogleResponse loginGoogle(GoogleIdTokenObject googleIdTokenObject, Optional<String> appId) {
        LoginGoogleRequest request =
            LoginGoogleRequest
                .builder()
                .googleIdTokenObject(googleIdTokenObject)
                .appId(appId)
                .build();
        RequestOperation<LoginGoogleRequest, LoginGoogleResponse> operation
              = new LoginGoogle.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * LoginNickname
     * 
     * <p>Returns a unique player token with a specified nickname for a user.
     * 
     * @return The call builder
     */
    public LoginNicknameRequestBuilder loginNickname() {
        return new LoginNicknameRequestBuilder(sdkConfiguration);
    }

    /**
     * LoginNickname
     * 
     * <p>Returns a unique player token with a specified nickname for a user.
     * 
     * @param nicknameObject 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LoginNicknameResponse loginNickname(NicknameObject nicknameObject) {
        return loginNickname(nicknameObject, Optional.empty());
    }

    /**
     * LoginNickname
     * 
     * <p>Returns a unique player token with a specified nickname for a user.
     * 
     * @param nicknameObject 
     * @param appId 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LoginNicknameResponse loginNickname(NicknameObject nicknameObject, Optional<String> appId) {
        LoginNicknameRequest request =
            LoginNicknameRequest
                .builder()
                .nicknameObject(nicknameObject)
                .appId(appId)
                .build();
        RequestOperation<LoginNicknameRequest, LoginNicknameResponse> operation
              = new LoginNickname.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
