/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.hathora.cloud_sdk;

import static dev.hathora.cloud_sdk.operations.Operations.RequestOperation;

import dev.hathora.cloud_sdk.models.operations.GetNodeRequest;
import dev.hathora.cloud_sdk.models.operations.GetNodeRequestBuilder;
import dev.hathora.cloud_sdk.models.operations.GetNodeResponse;
import dev.hathora.cloud_sdk.models.operations.ListProvisionedNodesRequest;
import dev.hathora.cloud_sdk.models.operations.ListProvisionedNodesRequestBuilder;
import dev.hathora.cloud_sdk.models.operations.ListProvisionedNodesResponse;
import dev.hathora.cloud_sdk.models.shared.Region;
import dev.hathora.cloud_sdk.operations.GetNode;
import dev.hathora.cloud_sdk.operations.ListProvisionedNodes;
import dev.hathora.cloud_sdk.utils.Headers;
import java.lang.String;
import java.util.Optional;


public class NodesV1 {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncNodesV1 asyncSDK;

    NodesV1(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncNodesV1(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncNodesV1 async() {
        return asyncSDK;
    }

    /**
     * GetNode
     * 
     * <p>Returns information about the node identified by `appId`.
     * 
     * @return The call builder
     */
    public GetNodeRequestBuilder getNode() {
        return new GetNodeRequestBuilder(sdkConfiguration);
    }

    /**
     * GetNode
     * 
     * <p>Returns information about the node identified by `appId`.
     * 
     * @param nodeId 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetNodeResponse getNode(String nodeId) {
        GetNodeRequest request =
            GetNodeRequest
                .builder()
                .nodeId(nodeId)
                .build();
        RequestOperation<GetNodeRequest, GetNodeResponse> operation
              = new GetNode.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * ListProvisionedNodes
     * 
     * <p>List nodes that are running or draining. Filter the array by optionally passing in a `region`.
     * 
     * @return The call builder
     */
    public ListProvisionedNodesRequestBuilder listProvisionedNodes() {
        return new ListProvisionedNodesRequestBuilder(sdkConfiguration);
    }

    /**
     * ListProvisionedNodes
     * 
     * <p>List nodes that are running or draining. Filter the array by optionally passing in a `region`.
     * 
     * @param fleetId 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListProvisionedNodesResponse listProvisionedNodes(String fleetId) {
        return listProvisionedNodes(fleetId, Optional.empty(), Optional.empty());
    }

    /**
     * ListProvisionedNodes
     * 
     * <p>List nodes that are running or draining. Filter the array by optionally passing in a `region`.
     * 
     * @param fleetId 
     * @param orgId 
     * @param region 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListProvisionedNodesResponse listProvisionedNodes(
            String fleetId, Optional<String> orgId,
            Optional<? extends Region> region) {
        ListProvisionedNodesRequest request =
            ListProvisionedNodesRequest
                .builder()
                .fleetId(fleetId)
                .orgId(orgId)
                .region(region)
                .build();
        RequestOperation<ListProvisionedNodesRequest, ListProvisionedNodesResponse> operation
              = new ListProvisionedNodes.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
