/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.hathora.cloud_api.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import com.hathora.cloud_api.models.errors.SDKError;
import com.hathora.cloud_api.utils.LazySingletonValue;
import com.hathora.cloud_api.utils.Utils;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapitools.jackson.nullable.JsonNullable;


public class GetLogsForProcessRequestBuilder {

    private GetLogsForProcessRequest request;
    private final SDKMethodInterfaces.MethodCallGetLogsForProcess sdk;

    public GetLogsForProcessRequestBuilder(SDKMethodInterfaces.MethodCallGetLogsForProcess sdk) {
        this.sdk = sdk;
    }

    public GetLogsForProcessRequestBuilder request(GetLogsForProcessRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetLogsForProcessResponse call() throws Exception {

        return sdk.getLogsForProcess(
            request);
    }
}
