/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.hathora.cloud_sdk.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import com.hathora.cloud_sdk.models.errors.SDKError;
import com.hathora.cloud_sdk.utils.LazySingletonValue;
import com.hathora.cloud_sdk.utils.Utils;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapitools.jackson.nullable.JsonNullable;


public class GetLobbyInfoRequestBuilder {

    private Optional<? extends String> appId = Optional.empty();
    private String roomId;
    private final SDKMethodInterfaces.MethodCallGetLobbyInfo sdk;

    public GetLobbyInfoRequestBuilder(SDKMethodInterfaces.MethodCallGetLobbyInfo sdk) {
        this.sdk = sdk;
    }
                
    public GetLobbyInfoRequestBuilder appId(String appId) {
        Utils.checkNotNull(appId, "appId");
        this.appId = Optional.of(appId);
        return this;
    }

    public GetLobbyInfoRequestBuilder appId(Optional<? extends String> appId) {
        Utils.checkNotNull(appId, "appId");
        this.appId = appId;
        return this;
    }

    public GetLobbyInfoRequestBuilder roomId(String roomId) {
        Utils.checkNotNull(roomId, "roomId");
        this.roomId = roomId;
        return this;
    }

    public GetLobbyInfoResponse call() throws Exception {

        return sdk.getLobbyInfo(
            appId,
            roomId);
    }
}
