name: Test Java SDK
on:
  pull_request:
    paths-ignore:
      - "applications/cirrus/**"
      - .github/workflows/ci-cirrus.yml
      - .github/workflows/autosucceed-ci-cirrus.yml
jobs:
  deploy:
    name: Test Java SDK
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
