name: Test Java SDK
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  deploy:
    name: Test Java SDK
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
